version: '3.5'

services:
  actual:
    container_name: actual
    image: actualbudget/actual-server:latest
    ports:
      - 5006:5006
    restart: always
    environment:
      TZ: America/Los_Angeles
    cap_add:
      - NET_BIND_SERVICE
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /mnt/hibiscus_storage/actual:/data
    networks:
      network:
        ipv4_address: 172.23.0.2

  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    ports:
      - 9925:9000
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      BASE_URL: https://mealie.hou.sh
      ALLOW_SIGNUP: false
      SMTP_HOST: ${MEALIE_SMTP_HOST}
      SMTP_PORT: 465
      SMTP_AUTH_STRATEGY: SSL
      SMTP_FROM_EMAIL: ${MEALIE_SMTP_FROM_EMAIL}
      SMTP_USER: ${MEALIE_SMTP_USER}
      SMTP_PASSWORD: ${MEALIE_SMTP_PASSWORD}
      THEME_LIGHT_PRIMARY: '#78C2AD'
      THEME_LIGHT_ACCENT: '#007A99'
      THEME_LIGHT_SECONDARY: '#CF8083'
      THEME_LIGHT_SUCCESS: '#56CC9D'
      THEME_LIGHT_INFO: '#6cc3d5'
      THEME_LIGHT_WARNING: '#ffce67'
      THEME_LIGHT_ERROR: '#ff7851'
      THEME_DARK_PRIMARY: '#78C2AD'
      THEME_DARK_ACCENT: '#007A99'
      THEME_DARK_SECONDARY: '#CF8083'
      THEME_DARK_SUCCESS: '#56CC9D'
      THEME_DARK_INFO: '#6cc3d5'
      THEME_DARK_WARNING: '#ffce67'
      THEME_DARK_ERROR: '#ff7851'
    volumes:
      - /mnt/hibiscus_storage/mealie/data/:/app/data
    networks:
      network:
        ipv4_address: 172.23.0.3
  
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16