version: '3.5'
services:
  homebridge:
    container_name: homebridge
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - /mnt/orchid_storage/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"

  adguardhome:
    container_name: adguard
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 8067:67/udp
      - 8068:68/udp
      - 8080:80/tcp
      - 8443:443/tcp
      - 8443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    environment:
      TZ: America/Los_Angeles
  volumes:
      - /mnt/lilac_storage/adguardhome/work:/opt/adguardhome/work
      - /mnt/lilac_storage/adguardhome/conf:/opt/adguardhome/conf
    cap_add:
      - NET_BIND_SERVICE
    restart: always
    networks:
      network:
        ipv4_address: 172.18.0.2

  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password --bind-address=172.18.0.3
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    restart: always
    volumes:
      - /mnt/lilac_storage/mysql/var/lib/mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 172.18.0.3

  nginx_proxy_manager:
    container_name: nginx_proxy_manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: '172.18.0.3'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: '${MYSQL_NGINX_USERNAME}'
      DB_MYSQL_PASSWORD: '${MYSQL_NGINX_PASSWORD}'
      DB_MYSQL_NAME: 'nginx_proxy_manager'
    volumes:
      - /mnt/lilac_storage/nginx_proxy_manager/data:/data
      - /mnt/lilac_storage/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - mysql
    networks:
      network:
        ipv4_address: 172.18.0.4

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16