version: '3.5'
services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password --bind-address=172.22.0.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
    restart: always
    volumes:
      - ./mysql/var/lib/mysql:/var/lib/mysql
    networks:
      base_network:
        ipv4_address: 172.22.0.7

  adminer:
    image: adminer
    restart: always
    ports:
      - 8999:8080
    networks:
      base_network:
        ipv4_address: 172.22.0.31

networks:
  base_network:
    external: true
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
