version: '3.5'

services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server:latest
    ports:
      - 19132:19132/udp
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      TZ: America/Los_Angeles
      EULA: 'TRUE'
      # ONLINE_MODE: 
      GAMEMODE: survival
      DIFFICULTY: normal
      ALLOW_LIST_USERS: ${MINECRAFT_ALLOW_LIST_USERS}
    volumes:
      - /mnt/jasmine_storage/minecraft/data:/data
    cap_add:
      - NET_BIND_SERVICE
    networks:
      network:
        ipv4_address: 172.24.0.2

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16