version: '3.5'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome:latest
    ports:
      - 53:53/tcp 
      - 53:53/udp
      - 8067:67/udp
      - 8068:68/udp
      - 8080:80/tcp 
      - 8443:443/tcp 
      - 8443:443/udp 
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp 
      - 853:853/udp 
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    environment:
      TZ: America/Los_Angeles
    volumes:
      - /mnt/orchid_storage/adguardhome/work:/opt/adguardhome/work
      - /mnt/orchid_storage/adguardhome/conf:/opt/adguardhome/conf
      - /mnt/orchid_storage/nginx_proxy_manager/letsencrypt/live/npm-4:/opt/adguardhome/certs
    cap_add:
      - NET_BIND_SERVICE
    restart: always
    networks:
      network:
        ipv4_address: 172.22.0.2

  wireguard:
    container_name: wireguard
    image: ghcr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      SERVERURL: ${WIREGUARD_SERVER_URL}
      SERVERPORT: 51820
      PEERS: ${WIREGUARD_PEERS}
      PEERDNS: 172.22.0.2 #DNS IP locally (Docker assigned)
    volumes:
      - /mnt/orchid_storage/wireguard/config:/config
      - /mnt/orchid_storage/wireguard/lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: always
    networks:
      network:
        ipv4_address: 172.22.0.3

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
