version: '3.5'
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
    volumes:
      - /mnt/orchid_storage/freshrss/config:/config
    ports:
      - '8888:80'
    restart: always
    networks:
      base_network:
        ipv4_address: 172.22.0.50

  nginx_proxy_manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: '172.22.0.30'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: '${MYSQL_NGINX_USERNAME}'
      DB_MYSQL_PASSWORD: '${MYSQL_NGINX_PASSWORD}'
      DB_MYSQL_NAME: 'nginx_proxy_manager'
    volumes:
      - /mnt/orchid_storage/nginx_proxy_manager/data:/data
      - /mnt/orchid_storage/nginx_proxy_manager/letsencrypt:/etc/letsencrypt
    networks:
      base_network:
        ipv4_address: 172.22.0.51

  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Los_Angeles
      RECIPE_PUBLIC: 'true'
      RECIPE_SHOW_NUTRITION: 'true'
      RECIPE_SHOW_ASSETS: 'true'
      RECIPE_LANDSCAPE_VIEW: 'true'
      RECIPE_DISABLE_COMMENTS: 'false'
      RECIPE_DISABLE_AMOUNT: 'false'

      # Gunicorn
      # WEB_CONCURRENCY: 2
      # WORKERS_PER_CORE: 0.5
      # MAX_WORKERS: 8
    volumes:
      - /mnt/orchid_storage/mealie/data/:/app/data
    networks:
      base_network:
        ipv4_address: 172.22.0.52

networks:
  base_network:
    external: true
